# Use the official Node.js image as the base image
FROM node:14

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json into the container
COPY package*.json ./

# Install application dependencies
RUN npm install

# Copy the rest of the application files into the container
COPY . .

# Expose the port on which the application will run (if applicable)
EXPOSE 3000

# Set the command to run your Node.js application
CMD ["node", "app.js"]
